# Dockerfile

FROM php:5.3-apache

# Enable Apache rewrite module (useful if your app uses .htaccess)
RUN a2enmod rewrite

# Set working directory to Apache root
WORKDIR /var/www/html

# Copy all project files into the container
COPY . /var/www/html/

# Make sure file permissions are okay
RUN chown -R www-data:www-data /var/www/html

# Expose Apache port
EXPOSE 80
